[[main]]
none = "none"

[[main]]
name = "Blog"
pageRef = "Blog"
identifier = "Blog"
weight = 1

[[main]]
name = "Quotes"
pageRef = "quotes"
identifier = "quotes"
weight = 2

[[main]]
name = "About"
pageRef = "About/_index"
identifier = "ABOUT"
weight = 4

[[main]]
name = "Me"
pageRef = "About/AboutMe"
parent = "ABOUT"
weight = 1

[[main]]
name = "The Blog"
pageRef = "About/AboutBlog"
parent = "ABOUT"
weight = 2

[[main]]
name = "My Career"
pageRef = "About/AboutCareer"
parent = "ABOUT"
weight = 3


[[main]]
name = "Bookshelf"
pageRef = "bookshelf"
identifier = "Bookshelf"
weight = 2

[[footer]]
none = "none"

[[footer]]
name = "Linkedin"
pre = "linkedin"
url = "https://www.linkedin.com/in/hadi-al-hassan-25012518a/"
identifier = "PasXWqqcJA"
weight = 9_999

[[footer]]
name = "Github"
pre = "Github"
url = "https://github.com/HadiAlHassan"
weight = "2"
